title: "Olimpíada Venezolana de Informática"
description: "Competencia anual de programación para estudiantes de bachillerato."
author: mathiassm
url:

twitter:
    username: ACInformaticas

facebook:
    app_id:
    publisher:
    admins:

logo: logo.png

social:
  links:
    - https://twitter.com/ACInformaticas

google_site_verification:

permalink: /:title/
encoding: "utf-8"
timezone: "America/Caracas"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: :compressed
