title: "Olimpíada Venezolana de Informática"
description: "Competencia anual de programación para estudiantes de bachillerato."
author: mathiassm
url:
permalink: 
encoding: "utf-8"
timezone: "America/Caracas"

twitter:
    username: ACInformaticas

facebook:
    app_id:
    publisher:
    admins:

logo: /images/ovi-logo.png

social:
  links:
    - https://twitter.com/ACInformaticas

google_site_verification:

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

host: 0.0.0.0

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: css
  style: :compressed

collections:
    miembros:
        output: true
        permalink: /:collection/:path/
    news:
    libros:
